sudo: required
services:
    - docker

before_install:
    - docker build -t moath/server -f Dockerfile.dev .

#script:
#    - docker run moath/server npm run test -- --coverage

deploy:
    on: # deploy on any updates on the master branch
        branch: master
    provider: heroku
    api_key:
        secure: "$Heroku_API_KEY"
