version: '3.6'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        #restart: always
        ports:
            - 5000:5000
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - PORT=5000
            - COOKIE_KEY='wrgbaewjrp23f65965246fd6fw6evasdvDSGwaegvrvbAwervb'
        env_file:
            - env.server
            - env.database
        command: ['npm', 'run', 'dev']
