version: '3.6'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        #restart: always
        ports:
            - 5000:5000
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - PORT=5000
        command: ["npm", "run", "start"]
